In [2]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
data={'Name':['Alice','Bob','Charlie'],
      'Age':[25,30,35],
      'City':['New York','Los Angeles','Chicago']}
series=pd.Series(data)
print(series)

Name               [Alice, Bob, Charlie]
Age                         [25, 30, 35]
City    [New York, Los Angeles, Chicago]
dtype: object

In [4]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
series=pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [1]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}
df = pd.DataFrame(data)
print(df)
print(type(df))
print(df['Name'])
df['Name']
print(df.loc[0])
print(df.iloc[0])
print(df.loc[0, 'Name'])
print(df.iloc[0, 0])
print(df.loc[0:2, 'Name'])
print(df.iloc[0:3, 0])
print(df.loc[df['Age'] > 30])
print(df[df['Age'] > 30])
print(df['Age'].mean())
print(df['Age'].sum())

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
<class 'pandas.DataFrame'>
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str
Name       Alice
Age           25
City    New York
Name: 0, dtype: object
Name       Alice
Age           25
City    New York
Name: 0, dtype: object
Alice
Alice
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
32.5
130

In [15]:
# print(df.loc[0])
# print(df.iloc[0])
print(df.iloc[0, 0])
# print(df.loc[0:2, 'Name'])
# print(df.iloc[0:3, 0])
# print(df.loc[df['Age'] > 30])
# print(df[df['Age'] > 30])
# print(df['Age'].mean())

Alice

In [7]:
import numpy as np
np.array(df)

array([['Alice', 25, 'New York'],
       ['Bob', 30, 'Los Angeles'],
       ['Charlie', 35, 'Chicago'],
       ['David', 40, 'Houston']], dtype=object)

In [16]:
### Data manipulation with pandas
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [18]:
df[df['Age'] > 30]

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

In [5]:
df["salary"] = [50000, 60000, 70000, 80000]
df

ValueError: Length of values (4) does not match length of index (3072)

In [4]:
df.drop('salary', axis=1, inplace=True)

KeyError: "['salary'] not found in axis"

In [26]:
df['Age']=df['Age'] + 1
df

      Name  Age         City
0    Alice   26     New York
1      Bob   31  Los Angeles
2  Charlie   36      Chicago
3    David   41      Houston

In [28]:
df.drop('Age', axis=1, inplace=True)
df

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [ ]:
df.describe()

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [37]:
obj2=pd.Series([1,2,4,5,-1,10],index=['a','b','c','d','e','f'])
obj2

a     1
b     2
c     4
d     5
e    -1
f    10
dtype: int64

In [40]:
obj2[obj2 > 0]
import numpy as np
obj2[obj2 > 0] * 2
obj2*2  
np.exp(obj2)

a        2.718282
b        7.389056
c       54.598150
d      148.413159
e        0.367879
f    22026.465795
dtype: float64

In [ ]:
obj2*2

In [6]:
import pandas as pd
df=pd.read_csv('dat_bmw.csv')
df.head(5)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

In [7]:
print("DATa Types\n",df.dtypes)

DATa Types
 Year                  int64
Month                 int64
Region                  str
Model                   str
Units_Sold            int64
Avg_Price_EUR         int64
Revenue_EUR           int64
BEV_Share           float64
Premium_Share       float64
GDP_Growth          float64
Fuel_Price_Index    float64
dtype: object

In [8]:
print("Statistical summery:\n",df.describe())

Statistical summery:
               Year        Month    Units_Sold  Avg_Price_EUR   Revenue_EUR  \
count  3072.000000  3072.000000   3072.000000    3072.000000  3.072000e+03
mean   2021.500000     6.500000   7980.288086   63854.561523  5.113995e+08
std       2.291661     3.452615   3174.917444   14655.891299  2.431185e+08
min    2018.000000     1.000000   2379.000000   40011.000000  1.045314e+08
25%    2019.750000     3.750000   5225.500000   54500.250000  3.125504e+08
50%    2021.500000     6.500000   7985.500000   63493.000000  4.808690e+08
75%    2023.250000     9.250000  10528.250000   71489.500000  6.709141e+08
max    2025.000000    12.000000  15914.000000   93994.000000  1.433482e+09

         BEV_Share  Premium_Share   GDP_Growth  Fuel_Price_Index
count  3072.000000    3072.000000  3072.000000       3072.000000
mean      0.107572      14.660234     3.057526          1.176224
std       0.058099       5.334604     1.018103          0.118123
min      -0.015000       5.090000     0.100000          0.920000
25%       0.057000      12.275000     2.370000          1.080000
50%       0.108000      16.260000     3.060000          1.180000
75%       0.157250      18.932500     3.852500          1.270000
max       0.223000      20.970000     5.820000          1.410000

In [9]:
df.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [14]:
###Handliing missing values
df.isnull().sum()

Year                0
Month               0
Region              0
Model               0
Units_Sold          0
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

In [16]:
df.groupby('Model')['Avg_Price_EUR'].agg(['mean','sum','count'])

                  mean       sum  count
Model
3 Series  47986.494792  18426814    384
5 Series  61935.234375  23783130    384
MINI      42064.046875  16152594    384
X3        58018.552083  22279124    384
X5        68940.979167  26473336    384
X7        92006.489583  35330492    384
i4        64919.351562  24929031    384
iX        74965.343750  28786692    384

In [7]:
for i in range(0,5):
    print(i,end=" ")

0 1 2 3 4

In [4]:
import pandas as pd
import numpy as np
obj=pd.Series(range(4),index=['d','b','a','c'])
obj.sort_index()

a    2
b    1
c    3
d    0
dtype: int64

In [5]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['Three','one'],columns=['d','a','b','c'])
frame.sort_index()

       d  a  b  c
Three  0  1  2  3
one    4  5  6  7

In [7]:
frame.sort_index(axis=1)

       a  b  c  d
Three  1  2  3  0
one    5  6  7  4

In [9]:
frame.sort_index(axis=1,ascending=False)

       d  c  b  a
Three  0  3  2  1
one    4  7  6  5

In [1]:
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Arjun", "Meera", "Rahul", "Ananya", "Vikram"],
    "Age": [22, 24, 21, 23, 25],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "City": ["Bangalore", "Mumbai", "Delhi", "Chennai", "Hyderabad"],
    "Salary": [35000, 42000, 30000, 39000, 45000]
}

In [2]:
import csv
with open("sample_data.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

In [ ]:
with open("sample_data.csv", "r", newline="") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['I', 'D']
['N', 'a', 'm', 'e']
['A', 'g', 'e']
['G', 'e', 'n', 'd', 'e', 'r']
['C', 'i', 't', 'y']
['S', 'a', 'l', 'a', 'r', 'y']

In [6]:
import pandas as pd
d=pd.read_csv("sample_data.csv")

ParserError: Error tokenizing data. C error: Expected 4 fields in line 4, saw 6

In [1]:
import pandas as pd

data = {
    "Item": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "Cost": [75000, 500, 1500, 12000, 2000],
    "Quantity": [1, 2, 1, 1, 2],
    "Date": ["2026-05-01", "2026-05-02", "2026-05-01", "2026-05-03", "2026-05-02"]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("items.csv", index=False)

print("CSV file created!")

CSV file created!

In [2]:
import pandas as pd

# Read CSV
df = pd.read_csv("items.csv")

# Convert Date column to datetime (important for filtering)
df["Date"] = pd.to_datetime(df["Date"])

# Ask user for date
user_date = input("Enter date (YYYY-MM-DD): ")

# Filter rows
filtered = df[df["Date"] == user_date]

print(filtered)

       Item   Cost  Quantity       Date
0    Laptop  75000         1 2026-05-01
2  Keyboard   1500         1 2026-05-01

In [6]:
import csv
import pandas as pd
!cat examples/ex1.csv
a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

cat: examples/ex1.csv: No such file or directory

NameError: name 'a' is not defined

In [1]:
with open("ex1.csv", "w") as file:
    file.write("a,b,c,d,message\n")
    file.write("1,2,3,4,hello\n")
    file.write("5,6,7,8,world\n")
    file.write("9,10,11,12,foo\n")

In [2]:
import pandas as pd

df = pd.read_csv("ex1.csv")

print(df)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
!pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.13/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip